version: '3'

#networks:
#  marketboro:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.21.10.0/24
#          gateway: 172.21.10.1

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
#    networks:
#      - default
#      - marketboro
#        ipv4_address: 172.21.10.2
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reserve
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      TZ: Asiz/Seoul
    volumes:
     - D:/docker/reserve/docker/mysql/mysql-init.d:/docker-entrypoint-initdb.d
     - D:/docker/reserve/docker/mysql/db:/var/lib/mysql
#     - D:/docker/reserve/data/mysql/mysql-files:/var/lib/mysql-files
    restart: always

  api-srv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-srv
    image: reserve-api
#    links:
#      - mysql
    depends_on:
      - mysql
#    networks:
#      - marketboro
#        ipv4_address: 172.21.10.3
    ports:
      - '8080:8080'
    expose:
      - 8080
#    restart: always
#    volumes:
#      - ../log:/var/log
#      - ../logs:/var/logs
#    environment:
#      DB_HOST: mysql-srv
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reserve?autoReconnect=true&useSSL=false
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 1234